### PR TITLE
Small updates to the Fourier Features

### PR DESCRIPTION
**Pull request by pabloppp**
First of all, thanks for taking the time to implement your own version of the alias-free GAN, it's really cool 🙇 
I am by no means an expert, but I wanted to propose a couple of changes for the FourierFeature:

- First of all, you were rotating `coord_h` and then using the rotated value to rotate `coord_w`, so I fixed that.

- Then, I set the coordinates to the range [-1, 1] so when the rotation is applied it will be performed around the center of the image instead of the edge.
Here's an example of a few channels of the Fourier features without and with a rotation applied using a [0, 1] range:
imageimage
And here with a [-1, 1] range:
imageimage

- Finally, I made it so the translation is dependent on the frequency of every signal since otherwise, the shift in the phase will be different at each waveform.
Here are 3 signals and the same signals shifted by 1 unit using a frequency-independent translation value:
imageimage
And here are the same 3 signals when using a frequency-dependent translation:
imageimage
As you can see, by having a frequency-dependent shift we can keep the 3 signals synced.

Hopefully, these changes result in a better relationship between the affine transformation of the FourierFeature and the output images 🤞

### CODE REVIEW

**Comment by rosinality** [comment]
I totally unnoticed about rotation bugs, and other two looks really nice. Thank you!

**Comment by rosinality** [comment]
By using your updates, the model translates the image much more cleanly with respect to shifts!

test1
test2

**Comment by pabloppp** [comment]
Awesome results!!!
There still seems to be some aliasing, right? Or are those artifacts caused by the GIF conversion?
I realized a few more things about how Fourier Features should be, just in case this helps: 

First of all, I noticed that if the coords are centered in 0 with the range [-1, 1] the critical-sampling cutoff frequency needs to be the width/4 and not width/2. You could either change the cutoff frequency, or maybe set the range to [-0.5, 0.5] so it's still centered in 0 but the length of the range is 1.

Second, maybe less relevant, in the paper, they say that the translation should be applied after the rotation around the center of the canvas. My interpretation of this is that visually one should first see the image rotated then translated from the rotated image, but the way it's being done right now in your code, visually, the translation happens first. 
In order for this to not happen, in the code, you would need to, first, add the translation values, and then, rotate the image (what in the code happens first, visually happens last).

Something like:
```python
coord_h_orig = coord_h.unsqueeze(0) - t_y * self.lf
coord_w_orig = coord_w.unsqueeze(0) - t_x * self.lf

coord_h = -coord_w_orig * r_s + coord_h_orig * r_c 
coord_w = coord_w_orig * r_c + coord_h_orig * r_s 
```

Again, awesome job! And awesome results! I am trying to do my own custom implementation and I only get garbage results (for now) 😓 it's awesome to see that my contributions helped you 🙇

**Comment by rosinality** [comment]
Yes, it seems like that aliasing mainly came from gif conversion. Original video seems much better: https://www.dropbox.com/s/0d29fzq3idrwg2j/test1.webm?dl=0 https://www.dropbox.com/s/q46mftab2965frn/test2.webm?dl=0

As authors said they have used width / 2, it seems like that [-0.5, 0.5] would be reasonable choice. I will try to apply it with rotation/translation orders. Thank you!

**Pull request merged**
